### ISSUE TITLE
请问大佬有对应的开发笔记吗

### ISSUE THREAD

**Issue by ghost** [WRCoding/nrpc#2]
想要学习下项目，有些地方看不要太明白。请问大佬有笔记或者文档什么的吗

**Comment by WRCoding** [comment]
暂时没有喔，有啥问题你在github或者邮件直接问我就好发自我的 iPhone在 2022年10月14日，11:13，Rylan ***@***.***> 写道：﻿
想要学习下项目，有些地方看不要太明白。请问大佬有笔记或者文档什么的吗
